# Generated by Django 3.0.3 on 2020-06-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_data',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=250)),
                ('book_image', models.ImageField(upload_to='book_images/')),
                ('Author_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
