# Generated by Django 3.0.3 on 2020-06-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('full_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
